// Make a List<Map<String, dynamic>> of Malawian cities with label and values

List<Map<String, dynamic>> malawiCities = [
  {'label': 'Blantyre', 'value': 'blantrye'},
  {'label': 'Chikwawa', 'value': 'chikwawa'},
  {'label': 'Chiradzulu', 'value': 'chiradzulu'},
  {'label': 'Chitipa', 'value': 'chitipa'},
  {'label': 'Dedza', 'value': 'dedza'},
  {'label': 'Dowa', 'value': 'dowa'},
  {'label': 'Karonga', 'value': 'karonga'},
  {'label': 'Kasungu', 'value': 'kasungu'},
  {'label': 'Likoma', 'value': 'likoma'},
  {'label': 'Lilongwe', 'value': 'lilongwe'},
  {'label': 'Machinga', 'value': 'machinga'},
  {'label': 'Mangochi', 'value': 'mangochi'},
  {'label': 'Mchinji', 'value': 'mcinji'},
  {'label': 'Mulanje', 'value': 'mulanje'},
  {'label': 'Mwanza', 'value': 'mwanza'},
  {'label': 'Mzimba', 'value': 'mzimba'},
  {'label': 'Nkhata Bay', 'value': 'nkhata bay'},
  {'label': 'Nkhotakota', 'value': 'nkhotakota'},
  {'label': 'Nsanje', 'value': 'nsanje'},
  {'label': 'Ntcheu', 'value': 'ntcheu'},
  {'label': 'Ntchisi', 'value': 'ntchisi'},
  {'label': 'Phalombe', 'value': 'phalombe'},
  {'label': 'Rumphi', 'value': 'rumphi'},
  {'label': 'Salima', 'value': 'salima'},
  {'label': 'Thyolo', 'value': 'thyolo'},
  {'label': 'Zomba', 'value': 'zomba'},
];
